"""
sandbox/sandbox.py
Abstract base class for sandbox environments.
Inspired by DeerFlow's sandbox architecture.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional


@dataclass
class CommandResult:
    """Result of a command execution in the sandbox."""
    stdout: str
    stderr: str
    exit_code: int
    success: bool

    @property
    def output(self) -> str:
        """Combined stdout + stderr for convenience."""
        if self.stderr:
            return f"{self.stdout}\nStdErr:\n{self.stderr}" if self.stdout else self.stderr
        return self.stdout or "(no output)"


# Dangerous shell patterns that could indicate injection attempts
_DANGEROUS_PATTERNS = [
    "$(",      # Command substitution
    "`",       # Backtick command substitution
    "&&",      # Command chaining
    "||",      # OR chaining
    ";",       # Command separator
    "|",       # Pipe
    "\n",      # Newline (command injection)
    "\r",      # Carriage return
]


class Sandbox(ABC):
    """Abstract base class for sandbox environments.

    A sandbox provides an isolated execution environment for running
    untrusted code generated by AI agents.
    """

    def __init__(self, sandbox_id: str):
        self._id = sandbox_id

    @property
    def id(self) -> str:
        return self._id

    @staticmethod
    def sanitize_command(command: str) -> str:
        """Sanitize command to prevent shell injection.

        Args:
            command: Raw command string.

        Returns:
            Sanitized command string.

        Raises:
            ValueError: If command contains dangerous patterns.
        """
        for pattern in _DANGEROUS_PATTERNS:
            if pattern in command:
                raise ValueError(
                    f"Unsafe command pattern detected: {pattern!r} "
                    f"in command: {command[:50]}..."
                )
        return command

    @abstractmethod
    async def run_command(self, command: str, timeout: int = 60) -> CommandResult:
        """Execute a shell command in the sandbox.

        Args:
            command: Shell command to execute.
            timeout: Timeout in seconds (default 60).

        Returns:
            CommandResult with stdout, stderr, exit_code.
        """
        pass

    @abstractmethod
    async def write_file(self, path: str, content: str) -> None:
        """Write content to a file inside the sandbox.

        Args:
            path: Absolute path inside sandbox.
            content: Text content to write.
        """
        pass

    @abstractmethod
    async def read_file(self, path: str) -> str:
        """Read a file from inside the sandbox.

        Args:
            path: Absolute path inside sandbox.

        Returns:
            File content as string.
        """
        pass

    @abstractmethod
    async def cleanup(self) -> None:
        """Clean up sandbox resources (containers, temp dirs, etc.)."""
        pass

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.cleanup()
